name: Build and push images

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run tag action
        uses: ejfitzgerald/action-docker-tag@95b02a1fa06c08bb2285a92294b6046b3b9ce95e
        with:
          repo: foobar
