name: Build and push images

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run tag action
        uses: ejfitzgerald/action-docker-tag@acac0a1ccea09beb3730482cb633fb907a5d4a23
        with:
          repo: foobar
